version: '3.8'

services:
  # Serviço para a aplicação Node.js
  app:
    build: .
    container_name: graphql-node-ts
    environment:
      - MONGO_URI=mongodb://mongo:27017/myapp
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]  
    
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=myapp
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
